name = "gigshub"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "gigshub-db"
database_id = "5975a6ae-df3c-44c3-a1c7-25d3b497ce51"

[dev]
ip = "*"
port = 8788